#[provider]
#cluster = "localnet"
#wallet = "~/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/home/bmstart/work/solana/keys/alice.json"


[programs.localnet]
multisig = "6nt4WQkt8Z5YPdj3HuqqvNBKnp8Chpv3WuMgdDA4XqzE"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[features]
